sudo: false

language: node_js
node_js: stable

install:
  - yarn install

script:
  - yarn test
  - npm run codecov

cache:
  yarn: true
  directories:
    - "node_modules"

branches:
  only:
    - master
