sudo: false

language: node_js
node_js: stable

install:
  - yarn install

script:
  - npm install codecov -g
  - yarn test

cache:
  yarn: true
  directories:
    - "node_modules"

after_success:
  - codecov

branches:
  only:
    - master
